In [1]:
import numpy as np

In [3]:
a = np.array([2,1,3])
b = np.array([1,3,3])
a,b

(array([2, 1, 3]), array([1, 3, 3]))

##### Addition and Subtraction

In [5]:
print(a+b)
print(a-b)

[3 4 6]
[ 1 -2  0]


##### Dot product

In [8]:
manual = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
formula = a@b
manual,formula

(np.int64(14), np.int64(14))

###### L2 norm(usual length)

In [9]:
print(np.linalg.norm(a))

3.7416573867739413


###### L1 norm(absoute length)

In [10]:
print(np.linalg.norm(a,ord=1))

6.0


###### Unit vector

In [15]:
unit_a = a/np.linalg.norm(a)
unit_a,np.linalg.norm(unit_a)

(array([0.53452248, 0.26726124, 0.80178373]), np.float64(1.0))

##### Euclidean vs Manhattan

In [17]:
x = np.array([
    [70,80],
    [60,90],
    [85,60],
    [78,76],
    [62,65]
],dtype=float)
q = np.array([75,70],dtype=float)

In [18]:
# euclidean distance(L2)
eu = np.linalg.norm(x-q, axis=1)
print('Euclidean distance',np.round(eu,3).tolist())

Euclidean distance [11.18, 25.0, 14.142, 6.708, 13.928]


In [19]:
# manhattan distance(L1)
man = np.linalg.norm(x-q, axis=1,ord = 1)
print('Manhattan distance',np.round(man,3).tolist())

Manhattan distance [15.0, 35.0, 20.0, 9.0, 18.0]
